__include__:
  [
    "../common/dataset/dut_anti_uav_detection.yml",
    "../common/runtime.yml",
    "../common/dataloader.yml",
    "../common/optimizer.yml",
    "../common/models/rtdetrv2_r18vd.yml",
  ]

output_dir: ./output/rtdetrv2_r18vd/dut_anti_uav/rtdetrv2_r18vd_144e_2e-1_dropout

epoches: 144

optimizer:
  type: AdamW
  params:
    - params: "^(?=.*(?:norm|bn)).*$"
      weight_decay: 0.

train_dataloader:
  dataset:
    transforms:
      policy:
        epoch: 141
  collate_fn:
    scales: ~

HybridEncoder:
  dropout: 0.2
RTDETRTransformerv2:
  dropout: 0.2
