__include__:
  [
    "../dataset/robust_dut_anti_uav_low_detection.yml",
    "../runtime.yml",
    "./include/robust_dataloader.yml",
    "./include/optimizer.yml",
    "./include/robust_rtdetrv2_r50vd.yml",
  ]

output_dir: ./output/rtdetrv2_r18vd/robust_dut_anti_uav_low/robust_rtdetrv2_r18vd_120e

PResNet:
  depth: 18
  freeze_at: 4
  freeze_norm: True
  pretrained: True

MultiScaleProcessor:
  modules:
    - { type: AMFG, embed_dims: 128, spatial_attention: 4 }
    - { type: AMFG, embed_dims: 256, spatial_attention: 4 }
    - { type: AMFG, embed_dims: 512, spatial_attention: 4 }

HybridEncoder:
  in_channels: [128, 256, 512]
  hidden_dim: 256
  expansion: 0.5

RTDETRTransformerv2:
  num_layers: 3

epoches: 120

optimizer:
  type: AdamW
  params:
    - params: "^(?=.*(?:norm|bn|BN|IN)).*$"
      weight_decay: 0.

train_dataloader:
  dataset:
    transforms:
      policy:
        epoch: 117
  collate_fn:
    scales: ~
