task: detection

evaluator:
  type: CocoEvaluator
  iou_types: ["bbox"]

# num_classes: 365
# remap_mscoco_category: False

# num_classes: 91
# remap_mscoco_category: False

num_classes: 1
remap_mscoco_category: False

val_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: ./dataset/Sim2Air/UAV-Eagle/images/
    ann_file: ./dataset/Sim2Air/UAV-Eagle/annotations/test.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~
  shuffle: False
  num_workers: 4
  drop_last: False
  collate_fn:
    type: BatchImageCollateFunction
