__include__:
  [
    "../common/dataset/dut_anti_uav_degraded_detection.yml",
    "../common/runtime.yml",
    "../common/robust_dataloader.yml",
    "../common/optimizer.yml",
    "../common/models/robust_rtdetrv2_r18vd.yml",
  ]

output_dir: ./output/rtdetrv2_r18vd/dut_anti_uav/robust_rtdetrv2_r18vd_120e_denet_from_scratch

RobustRTDETR:
  train_all: true
  robust_image_module: DENet
  robust_module: ~

PResNet:
  freeze_at: -1
  freeze_norm: false

DENet:
  # original code bug: mm1 used for all 4 branches
  # compat_mode=True => their config in source code
  # compat_mode=False => their config in paper
  compat_mode: false

RobustCriterion:
  # image_cst_loss:
  #   type: MSELoss
  #   reduction: none
  image_cst_loss: ~
  cst_loss: ~
  weight_dict:
    loss_image_cst: 20
    loss_cst: 20

epoches: 120

optimizer:
  type: AdamW
  params:
    - params: "^(?=.*(?:norm|bn|BN|IN)).*$"
      weight_decay: 0.

train_dataloader:
  dataset:
    transforms:
      ops:
        - { type: RandomPhotometricDistort, p: 0.5 }
        - { type: RandomZoomOut, fill: 0 }
        - { type: RandomIoUCrop, p: 0.8 }
        - { type: SanitizeBoundingBoxes, min_size: 1 }
        - { type: RandomHorizontalFlip }
        - { type: Resize, size: [640, 640] }
        - { type: SanitizeBoundingBoxes, min_size: 1 }
        - { type: ConvertPILImage, dtype: "float32", scale: True }
        - { type: ConvertBoxes, fmt: "cxcywh", normalize: True }
      policy:
        ops: ["RandomPhotometricDistort", "RandomZoomOut", "RandomIoUCrop"]
        epoch: 117
  collate_fn:
    scales: ~
