__include__:
  [
    "../common/dataset/dut_anti_uav_degraded_detection.yml",
    "../common/runtime.yml",
    "../common/robust_dataloader.yml",
    "../common/optimizer.yml",
    "../common/models/robust_rtdetrv2_r18vd.yml",
  ]

output_dir: ./output/rtdetrv2_r18vd/dut_anti_uav/robust_rtdetrv2_r18vd_50e_5e-4_lr_spatial_afr_relu_no_train_heads_mixed_selection

RobustRTDETR:
  train_heads: False

# MultiScaleProcessor:
#   modules:
#     - { type: SimpleNN, embed_dims: 128 }
#     - { type: SimpleNN, embed_dims: 256 }
#     - { type: SimpleNN, embed_dims: 512 }

# MultiScaleProcessor:
#   modules:
#     - { type: AMFGv2, embed_dims: 128 }
#     - { type: AMFGv2, embed_dims: 256 }
#     - { type: AMFGv2, embed_dims: 512 }

# MultiScaleProcessor:
#   modules:
#     - { type: SpatialAMFGv2, embed_dims: 128 }
#     - { type: SpatialAMFGv2, embed_dims: 256 }
#     - { type: SpatialAMFGv2, embed_dims: 512 }

# MultiScaleProcessor:
#   modules:
#     - { type: AFR, embed_dims: 128 }
#     - { type: AFR, embed_dims: 256 }
#     - { type: AFR, embed_dims: 512 }

# MultiScaleProcessor:
#   modules:
#     - { type: AFR, embed_dims: 128, activation: ReLU }
#     - { type: AFR, embed_dims: 256, activation: ReLU }
#     - { type: AFR, embed_dims: 512, activation: ReLU }

# MultiScaleProcessor:
#   modules:
#     - { type: SpatialAFR, embed_dims: 128 }
#     - { type: SpatialAFR, embed_dims: 256 }
#     - { type: SpatialAFR, embed_dims: 512 }

MultiScaleProcessor:
  modules:
    - { type: SpatialAFR, embed_dims: 128, activation: ReLU }
    - { type: SpatialAFR, embed_dims: 256, activation: ReLU }
    - { type: SpatialAFR, embed_dims: 512, activation: ReLU }

# MultiScaleProcessor:
#   modules:
#     - {
#         type: SpatialAFR,
#         embed_dims: 128,
#         activation: ReLU,
#         spatial_fusion_cfg: { bias: True },
#       }
#     - {
#         type: SpatialAFR,
#         embed_dims: 256,
#         activation: ReLU,
#         spatial_fusion_cfg: { bias: True },
#       }
#     - {
#         type: SpatialAFR,
#         embed_dims: 512,
#         activation: ReLU,
#         spatial_fusion_cfg: { bias: True },
#       }

# MultiScaleProcessor:
#   modules:
#     - type: SpatialAFR
#       embed_dims: 128
#       spatial_cfg: { conv: False, activation: ~ }
#       activation: ReLU

#     - type: SpatialAFR
#       embed_dims: 256
#       spatial_cfg: { conv: False, activation: ~ }
#       activation: ReLU

#     - type: SpatialAFR
#       embed_dims: 512
#       spatial_cfg: { conv: False, activation: ~ }
#       activation: ReLU

# RobustCriterion:
#   cst_loss: ~

# criterion: RobustCriterionv2
# RobustCriterionv2:
#   model_loss: RTDETRCriterionv2
#   content_loss:
#     type: MSELoss
#     reduction: none
#   style_loss:
#     type: MSELoss
#     reduction: none
#   weight_dict:
#     loss_content: 20
#     loss_style: 20

epoches: 50

optimizer:
  type: AdamW
  lr: 0.0005
  params:
    - params: "^(?=.*(?:norm|bn|BN|IN)).*$"
      weight_decay: 0.

# lr_scheduler:
#   type: MultiStepLR
#   milestones: [100]
#   gamma: 0.1

train_dataloader:
  dataset:
    transforms:
      policy:
        epoch: 47
  collate_fn:
    scales: ~

val_dataloader:
  dataset:
    ann_file: ./dataset/DUT_Anti_UAV/detection/annotations/mixed_val.json

val_train_dataloader:
  dataset:
    transforms:
      ops:
        - { type: Degradation, identity: True }
        - { type: Resize, size: [640, 640] }
        - { type: ConvertPILImage, dtype: "float32", scale: True }
