__include__:
  [
    "../common/dataset/dut_anti_uav_detection.yml",
    "../common/runtime.yml",
    "../common/dataloader.yml",
    "../common/optimizer.yml",
    "../common/models/rtdetrv2_r18vd.yml",
  ]

output_dir: ./output/rtdetrv2_r18vd/dut_anti_uav/rtdetrv2_r18vd_120e_no_color_augs_in_clear

epoches: 120

optimizer:
  type: AdamW
  params:
    - params: "^(?=.*(?:norm|bn)).*$"
      weight_decay: 0.
  # weight_decay: 0.1

# train_dataloader:
#   dataset:
#     transforms:
#       policy:
#         epoch: 117
#   collate_fn:
#     scales: ~

train_dataloader:
  dataset:
    transforms:
      ops:
        - { type: RandomZoomOut, fill: 0 }
        - { type: RandomIoUCrop, p: 0.8 }
        - { type: SanitizeBoundingBoxes, min_size: 1 }
        - { type: RandomHorizontalFlip }
        - { type: Resize, size: [640, 640] }
        - { type: SanitizeBoundingBoxes, min_size: 1 }
        - { type: ConvertPILImage, dtype: "float32", scale: True }
        - { type: ConvertBoxes, fmt: "cxcywh", normalize: True }
      policy:
        epoch: 117
        ops: ["RandomZoomOut", "RandomIoUCrop"]
  collate_fn:
    scales: ~

# HybridEncoder:
#   dropout: 0.2
# RTDETRTransformerv2:
#   dropout: 0.2

# lr_warmup_scheduler:
#   type: LinearWarmup
#   warmup_duration: 1625
