__include__:
  [
    "../base/dataset/coco_detection.yml",
    "../common/runtime.yml",
    "../common/dataloader.yml",
    "../common/optimizer.yml",
    "../common/models/rtdetrv2_r18vd.yml",
  ]

output_dir: ./output/rtdetrv2_r18vd/coco/rtdetrv2_r18vd_144e

epoches: 144

optimizer:
  type: AdamW
  params:
    - params: "^(?=.*(?:norm|bn)).*$"
      weight_decay: 0.

train_dataloader:
  dataset:
    transforms:
      policy:
        epoch: 141
  collate_fn:
    scales: ~

val_train_dataloader: ~
