__include__:
  [
    "../base/dataset/coco_detection.yml",
    "../common/runtime.yml",
    "../common/dataloader.yml",
    "../common/optimizer.yml",
    "../common/models/rtdetrv2_r50vd.yml",
  ]

output_dir: ./output/rtdetrv2_r50vd/coco/rtdetrv2_r50vd_84e_m_7x

HybridEncoder:
  expansion: 0.5

RTDETRTransformerv2:
  eval_idx: 2 # use 3th decoder layer to eval

epoches: 84

optimizer:
  type: AdamW
  params:
    - params: "^(?=.*backbone)(?!.*norm).*$"
      lr: 0.00001
    - params: "^(?=.*(?:encoder|decoder))(?=.*(?:norm|bn)).*$"
      weight_decay: 0.

  lr: 0.0001
  betas: [0.9, 0.999]
  weight_decay: 0.0001

train_dataloader:
  dataset:
    transforms:
      policy:
        epoch: 81
  collate_fn:
    stop_epoch: 81

val_train_dataloader: ~
