__include__: ["./rtdetrv2_r50vd.yml"]

model: RobustRTDETR
criterion: RobustCriterion

RobustRTDETR:
  backbone: PResNet
  robust_module: MultiScaleProcessor
  encoder: HybridEncoder
  decoder: RTDETRTransformerv2

PResNet:
  freeze_at: 4
  freeze_norm: True

MultiScaleProcessor:
  modules:
    - { type: AMFG, embed_dims: 512, spatial_attention: 4 }
    - { type: AMFG, embed_dims: 1024, spatial_attention: 4 }
    - { type: AMFG, embed_dims: 2048, spatial_attention: 4 }

RobustCriterion:
  model_loss: RTDETRCriterionv2
  cst_loss:
    type: MSELoss
    reduction: none
  weight_dict:
    loss_cst: 20
