__include__:
  [
    "../common/dataset/robust_dut_anti_uav_low_detection.yml",
    "../common/runtime.yml",
    "../common/robust_dataloader.yml",
    "../common/optimizer.yml",
    "../common/models/robust_rtdetrv2_r18vd.yml",
  ]

output_dir: ./output/rtdetrv2_r18vd/robust_dut_anti_uav_low/robust_rtdetrv2_r18vd_50e_2

epoches: 50

optimizer:
  type: AdamW
  params:
    - params: "^(?=.*(?:norm|bn|BN|IN)).*$"
      weight_decay: 0.

# lr_scheduler:
#   type: MultiStepLR
#   milestones: [100]
#   gamma: 0.1

train_dataloader:
  dataset:
    transforms:
      policy:
        epoch: 47
  collate_fn:
    scales: ~
